const steps = [
  { name: 'First impression', title: 'What’s the overall energy of it?', copy: 'Choose anything that feels close. You can keep more than one.', options: [['Low-key', 'Quiet, slowed down, or inward'], ['Activated', 'Restless, charged, or on edge'], ['Heavy', 'A weight you can feel'], ['Light', 'Open, easy, or lifted']] },
  { name: 'The texture', title: 'What does it feel most like?', copy: 'There may be more than one thing happening. Follow the thread that calls to you.', options: [['Uncertain', 'You can’t quite see what comes next'], ['Disconnected', 'A little removed from yourself or others'], ['Pressured', 'There’s something asking a lot of you'], ['Tender', 'Sensitive, exposed, or easily touched']] },
  { name: 'A closer word', title: 'Which of these feels nearest?', copy: 'Try the words on. Keep anything that creates even a small “yes.”', options: [['Apprehensive', 'Expecting something difficult or uncertain'], ['Restless', 'Finding it hard to settle or stay still'], ['Drained', 'Your energy feels used up'], ['Hopeful', 'A small sense that things could get better']] }
];
const related = { 'Low-key':['Tired','Reflective'], Activated:['Restless','Tense'], Heavy:['Drained','Discouraged'], Light:['Hopeful','Content'], Uncertain:['Apprehensive','Ambivalent'], Disconnected:['Distant','Lonely'], Pressured:['Overwhelmed','Urgent'], Tender:['Vulnerable','Sensitive'], Apprehensive:['Uneasy','Worried'], Restless:['Agitated','Impatient'], Drained:['Exhausted','Spent'], Hopeful:['Encouraged','Optimistic'] };
let step = 0, palette = new Map(), picture = new Set();
const $ = id => document.getElementById(id);
function renderStep(){ const s=steps[step]; $('step-label').textContent=`0${step+1} / 03`; $('step-name').textContent=s.name; $('progress-fill').style.width=`${(step+1)*33.33}%`; $('question-title').textContent=s.title; $('question-copy').textContent=s.copy; $('option-grid').innerHTML=s.options.map(([name,desc])=>`<button class="option ${palette.has(name)?'selected':''}" data-name="${name}"><span class="option-dot">✓</span><strong>${name}</strong><small>${desc}</small></button>`).join(''); document.querySelectorAll('.option').forEach(b=>b.onclick=()=>togglePalette(b.dataset.name)); }
function togglePalette(name){ if(palette.has(name)) palette.delete(name); else palette.set(name,{name,desc:findDesc(name)}); renderPalette(); renderStep(); }
function findDesc(name){ for(const s of steps){const found=s.options.find(x=>x[0]===name);if(found)return found[1]} return 'A feeling in the mix'; }
function renderPalette(){ $('palette-count').textContent=palette.size; $('palette-list').innerHTML=palette.size?[...palette.values()].map(t=>`<span class="tag">${t.name}<button aria-label="Remove ${t.name}" data-remove="${t.name}">×</button></span>`).join(''):`<div class="empty-state">Your palette will appear here.<br><span>Follow what feels even a little true.</span></div>`; document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{palette.delete(b.dataset.remove);renderPalette();renderStep()}); }
function begin(){step=0;palette.clear();picture.clear();$('home-view').classList.add('hidden');$('picture-view').classList.add('hidden');$('explore-view').classList.remove('hidden');renderStep();renderPalette()}
function next(){ if(step<steps.length-1){ const before=[...palette.keys()]; before.forEach(n=>(related[n]||[]).forEach(x=>{if(!palette.has(x))palette.set(x,{name:x,desc:findDesc(x)})}));step++;renderStep();renderPalette(); } else showPicture(); }
function showPicture(){ picture=new Set([...palette.keys()].filter(n=>steps[2].options.some(x=>x[0]===n)||['Uneasy','Worried','Agitated','Impatient','Exhausted','Spent','Encouraged','Optimistic'].includes(n))); if(!picture.size) picture=new Set(palette.keys()); $('explore-view').classList.add('hidden');$('home-view').classList.add('hidden');$('picture-view').classList.remove('hidden');$('picture-list').innerHTML=[...picture].map(n=>`<span class="picture-word">${n}<small>${palette.get(n)?.desc||''}</small></span>`).join('');}
function home(){step=0;palette.clear();picture.clear();$('explore-view').classList.add('hidden');$('picture-view').classList.add('hidden');$('home-view').classList.remove('hidden')}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>({begin,next,continue:next,showPicture,home,explore:()=>{$('picture-view').classList.add('hidden');$('explore-view').classList.remove('hidden')}}[b.dataset.action]||(()=>{}))()));
renderPalette();
