const steps = [
  { name: 'First impression', title: 'What’s the overall energy of it?', copy: 'Choose anything that feels close. You can keep more than one.', options: [['Low-key', 'Quiet, slowed down, or inward'], ['Activated', 'Restless, charged, or on edge'], ['Heavy', 'A weight you can feel'], ['Light', 'Open, easy, or lifted']] },
  { name: 'The texture', title: 'What does it feel most like?', copy: 'There may be more than one thing happening. Follow the thread that calls to you.', options: [['Uncertain', 'You can’t quite see what comes next'], ['Disconnected', 'A little removed from yourself or others'], ['Pressured', 'There’s something asking a lot of you'], ['Tender', 'Sensitive, exposed, or easily touched']] },
  { name: 'A closer word', title: 'Which of these feels nearest?', copy: 'Try the words on. Keep anything that creates even a small “yes.”', options: [['Apprehensive', 'Expecting something difficult or uncertain'], ['Restless', 'Finding it hard to settle or stay still'], ['Drained', 'Your energy feels used up'], ['Hopeful', 'A small sense that things could get better']] }
];
const related = { 'Low-key':['Tired','Reflective'], Activated:['Restless','Tense'], Heavy:['Drained','Discouraged'], Light:['Hopeful','Content'], Uncertain:['Apprehensive','Ambivalent'], Disconnected:['Distant','Lonely'], Pressured:['Overwhelmed','Urgent'], Tender:['Vulnerable','Sensitive'], Apprehensive:['Uneasy','Worried'], Restless:['Agitated','Impatient'], Drained:['Exhausted','Spent'], Hopeful:['Encouraged','Optimistic'] };
let step = 0, palette = new Map(), picture = new Set();
const $ = id => document.getElementById(id);
const blobPaths = [
  'M24 52 C26 27 48 16 71 23 C94 10 125 20 132 42 C151 55 143 83 122 90 C109 108 77 104 61 94 C35 96 18 78 24 52Z',
  'M20 57 C18 34 38 20 61 23 C78 8 111 17 119 35 C144 36 151 65 132 78 C127 101 95 107 76 96 C53 106 22 91 20 57Z',
  'M29 39 C41 17 70 16 87 26 C109 15 137 29 136 52 C150 72 128 94 108 91 C90 109 57 101 49 86 C25 82 16 57 29 39Z',
  'M22 48 C24 24 53 13 75 25 C95 12 126 22 130 46 C151 57 141 87 117 91 C102 108 69 102 57 91 C31 97 14 74 22 48Z'
];
function blobSvg(index){ const circles=[[48,50,28],[81,42,31],[106,63,27],[65,75,29]][index%4]; return `<svg class="blob-svg" viewBox="0 0 160 120" aria-hidden="true"><g class="blob-circles"><circle cx="${circles[0]}" cy="${circles[1]}" r="${circles[2]}"/><circle cx="82" cy="49" r="27"/><circle cx="109" cy="67" r="23"/></g><path d="${blobPaths[index%blobPaths.length]}"/></svg>`; }
function renderStep(){ const s=steps[step]; $('step-label').textContent=`0${step+1} / 03`; $('step-name').textContent=s.name; $('progress-fill').style.width=`${(step+1)*33.33}%`; $('question-title').textContent=s.title; $('question-copy').textContent=s.copy; $('option-grid').innerHTML=s.options.map(([name,desc],i)=>`<button class="option ${palette.has(name)?'selected':''}" data-name="${name}">${blobSvg(i)}<span class="option-content"><span class="option-dot">✓</span><strong>${name}</strong><small>${desc}</small></span></button>`).join(''); document.querySelectorAll('.option').forEach(b=>b.onclick=()=>togglePalette(b.dataset.name)); }
function togglePalette(name){ if(palette.has(name)) palette.delete(name); else palette.set(name,{name,desc:findDesc(name)}); renderPalette(); renderStep(); }
function findDesc(name){ for(const s of steps){const found=s.options.find(x=>x[0]===name);if(found)return found[1]} return 'A feeling in the mix'; }
function renderPalette(){ $('palette-count').textContent=palette.size; $('palette-list').innerHTML=palette.size?[...palette.values()].map(t=>`<span class="tag">${t.name}<button aria-label="Remove ${t.name}" data-remove="${t.name}">×</button></span>`).join(''):`<div class="empty-state">Your palette will appear here.<br><span>Follow what feels even a little true.</span></div>`; document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{palette.delete(b.dataset.remove);renderPalette();renderStep()}); }
function begin(){step=0;palette.clear();picture.clear();$('home-view').classList.add('hidden');$('picture-view').classList.add('hidden');$('explore-view').classList.remove('hidden');renderStep();renderPalette()}
function next(){ if(step<steps.length-1){ const before=[...palette.keys()]; before.forEach(n=>(related[n]||[]).forEach(x=>{if(!palette.has(x))palette.set(x,{name:x,desc:findDesc(x)})}));step++;renderStep();renderPalette(); } else showPicture(); }
function showPicture(){ picture=new Set([...palette.keys()].filter(n=>steps[2].options.some(x=>x[0]===n)||['Uneasy','Worried','Agitated','Impatient','Exhausted','Spent','Encouraged','Optimistic'].includes(n))); if(!picture.size) picture=new Set(palette.keys()); $('explore-view').classList.add('hidden');$('home-view').classList.add('hidden');$('picture-view').classList.remove('hidden');$('picture-list').innerHTML=[...picture].map(n=>`<span class="picture-word">${n}<small>${palette.get(n)?.desc||''}</small></span>`).join('');}
function home(){step=0;palette.clear();picture.clear();$('explore-view').classList.add('hidden');$('picture-view').classList.add('hidden');$('home-view').classList.remove('hidden')}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>({begin,next,continue:next,picture:showPicture,showPicture,home,explore:()=>{$('picture-view').classList.add('hidden');$('explore-view').classList.remove('hidden')}}[b.dataset.action]||(()=>{}))()));
renderPalette();
