const emotions=[['Tender','Sensitive, exposed, or easily touched'],['Restless','Finding it hard to settle or stay still'],['Apprehensive','Expecting something difficult or uncertain'],['Drained','Your energy feels used up'],['Distant','A little removed from yourself or others'],['Hopeful','A small sense that things could get better'],['Overwhelmed','More is coming at you than you can hold'],['Curious','Pulled toward something you don’t yet know'],['Lonely','Wanting closeness or company'],['Irritated','A small friction that won’t let go'],['Proud','Warmly aware of something you’ve done'],['Uncertain','You can’t quite see what comes next'],['Relieved','The pressure has begun to lift'],['Vulnerable','Open in a way that feels unprotected'],['Discouraged','Your energy or confidence has dipped']];
const palette=new Map();let focused=null,streamTimer=null;const $=s=>document.querySelector(s);
const paths=['M20 57C18 34 38 20 61 23C78 8 111 17 119 35C144 36 151 65 132 78C127 101 95 107 76 96C53 106 22 91 20 57Z','M24 52C26 27 48 16 71 23C94 10 125 20 132 42C151 55 143 83 122 90C109 108 77 104 61 94C35 96 18 78 24 52Z','M29 39C41 17 70 16 87 26C109 15 137 29 136 52C150 72 128 94 108 91C90 109 57 101 49 86C25 82 16 57 29 39Z'];
function blob(i){return `<svg viewBox="0 0 160 120" aria-hidden="true"><g class="blob-circles"><circle cx="48" cy="50" r="28"/><circle cx="82" cy="49" r="27"/><circle cx="109" cy="67" r="23"/></g><path d="${paths[i%3]}"/></svg>`}
function start(){ $('#home-view').classList.add('hidden');$('#palette-view').classList.add('hidden');$('#stream-view').classList.remove('hidden');renderStream() }
function renderStream(){clearTimeout(streamTimer);const layer=$('#cloud-layer');layer.innerHTML='';const used=new Set(palette.keys());const available=emotions.filter(e=>!used.has(e[0]));available.slice(0,3).forEach((e,i)=>{const b=document.createElement('button');b.className=`emotion-cloud cloud-${i}`;b.dataset.word=e[0];b.innerHTML=`${blob(i)}<span><strong>${e[0]}</strong><small>${e[1]}</small></span>`;b.onclick=()=>decide(e[0],'maybe');attachSwipe(b,e[0]);layer.appendChild(b)});focused=layer.querySelector('.cloud-1')||layer.firstElementChild;if(focused)focused.classList.add('focused');streamTimer=setTimeout(()=>{if(focused){focused.classList.add('fading');setTimeout(()=>{focused.remove();renderStream()},650)}},5000)}
function decide(word,response){const e=emotions.find(x=>x[0]===word);palette.set(word,{word,desc:e?.[1]||'',response});renderPaletteCount();const cloud=document.querySelector(`[data-word="${word}"]`);if(cloud){cloud.classList.add(`exit-${response}`);setTimeout(renderStream,430)}}
function renderPaletteCount(){$('#palette-count').textContent=palette.size}
function showPalette(){$('#stream-view').classList.add('hidden');$('#home-view').classList.add('hidden');$('#palette-view').classList.remove('hidden');renderCluster()}
function renderCluster(){const layer=$('#cluster-layer');layer.innerHTML='';$('#canvas-empty').classList.toggle('hidden',palette.size>0);[...palette.values()].forEach((x,i)=>{const b=document.createElement('button');b.className=`cluster-cloud response-${x.response}`;b.dataset.word=x.word;b.style.left=`${25+(i*37)%58}%`;b.style.top=`${12+(i*29)%68}%`;b.innerHTML=`${blob(i)}<span><strong>${x.word}</strong><small>${x.desc}</small></span>`;b.title='Drag to arrange';makeDraggable(b);layer.appendChild(b)})}
function makeDraggable(el){let down=false,ox=0,oy=0;el.onpointerdown=e=>{down=true;el.setPointerCapture(e.pointerId);ox=e.clientX-el.offsetLeft;oy=e.clientY-el.offsetTop;el.classList.add('dragging')};el.onpointermove=e=>{if(!down)return;const r=$('#palette-canvas').getBoundingClientRect();el.style.left=`${Math.max(4,Math.min(88,(e.clientX-r.left-ox)/r.width*100))}%`;el.style.top=`${Math.max(5,Math.min(88,(e.clientY-r.top-oy)/r.height*100))}%`};el.onpointerup=()=>{down=false;el.classList.remove('dragging')}}
function minimize(){document.querySelectorAll('.cluster-cloud').forEach((el,i)=>{if(i>0&&i%3===0)el.classList.add('condensed')})}
function home(){clearTimeout(streamTimer);palette.clear();$('#stream-view').classList.add('hidden');$('#palette-view').classList.add('hidden');$('#home-view').classList.remove('hidden');renderPaletteCount()}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>({home,start,begin:start,palette:showPalette,stream:()=>{$('#palette-view').classList.add('hidden');$('#stream-view').classList.remove('hidden');renderStream()},minimize}[b.dataset.action]||(()=>{}))());
document.addEventListener('keydown',e=>{if($('#stream-view').classList.contains('hidden')||!focused)return;const map={ArrowLeft:'not',ArrowRight:'maybe',ArrowUp:'definitely',ArrowDown:'definitely-not'};if(map[e.key]){e.preventDefault();decide(focused.dataset.word,map[e.key])}});renderPaletteCount();
function attachSwipe(b,word){let sx=0,sy=0;b.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY});b.addEventListener('pointerup',e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<35)return;const response=Math.abs(dx)>Math.abs(dy)?(dx<0?'not':'maybe'):(dy<0?'definitely':'definitely-not');decide(word,response)})}
